name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Bug is a problem which impairs or prevents the functions of the launcher from working as intended.
        Thanks for taking the time to fill out a bug report! 
        Please provide as much information as you can to help us understand and reproduce the issue.
        
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Tell us what you see! The more detail the better."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: proof
    attributes:
      label: Screenshots/Recordings
      description: If applicable, add Screenshots/Recordings to help explain your problem.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the launcher are you running?
      placeholder: "e.g. \"v2.2.1\""
    validations:
      required: true

  - type: textarea
    id: hardwarespec
    attributes:
      label: Hardware Specification
      description: Tell us your CPU, iGPU, dGPU, VRAM, and RAM information.
      placeholder: "CPU: Intel i9-14900K 6.0 GHz | GPU: NVIDIA RTX 4090 24 GB VRAM | RAM: 32 GB"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11/10
        - macOS (Apple Silicon, M1/M2/M3)
        - Linux Ubuntu/Debian-based (Linux Mint, Pop!_OS, etc.)
        - Linux Fedora/RHEL-based (Fedora, CentOS, etc.)
        - Linux Arch-based (Steamdeck, CachyOS, etc.)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, paste any error messages or logs here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
