name: Support Request
description: Request help or support
title: "[SUPPORT] <ADD YOUR TITLE HERE>"
labels: ["support"]
body:
  - type: dropdown
    id: acknowledge
    attributes: 
      label: Checklist
      options:
        - label: I have read the README.md before asking Support Request.
          required: true
        - label: I have read the TROUBLESHOOTING.md before asking Support Request.
          required: true
        - label: I have added title before submitting this Support Request.
          required: true
        - label: I acknowledge that my Support Request will not be responded as quick as in Discord Open-A-Ticket, I prefer this way.
          required: true

  - type: markdown
    attributes:
      value: |
        If you need help or support with using the launcher, please fill out this support request.
        Provide as much detail as possible so we can assist you effectively.
        **Need a quick assistance?** Please Open-A-Ticket in our [Discord Server](https://discord.gg/gME8rUy3MB)!

  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
      description: Describe your question or issue clearly.
      placeholder: "I'm having trouble with..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information.
      placeholder: "I've tried these steps, but got..."
    validations:
      required: true

  - type: textarea
    id: hardwarespec
    attributes:
      label: Hardware Specification
      description: Tell us your CPU, iGPU, dGPU, VRAM, and RAM information.
      placeholder: "CPU: Intel i9-14900K 6.0 GHz | GPU: NVIDIA RTX 4090 | VRAM: 24 GB | RAM: 32 GB"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you using?
      options:
        - v2.1.2
        - v2.1.1
        - v2.1.0
        - v2.0.11
        - v2.0.2
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows 11 x64
        - Windows 10 x64
        - macOS ARM64 (Apple Silicon)
        - Linux x64 Ubuntu/Debian-based
        - Linux x64 Fedora/RHEL-based
        - Linux x64 Arch-based
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, paste any error messages or logs here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might help us assist you.
